# Generated by Django 2.2.5 on 2019-09-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('minimum_qualification', models.CharField(choices=[('Dp', 'Diploma'), ('Bs', 'Bachelor'), ('Ms', 'Masters'), ('Ct', 'Certificate'), ('Ph', 'PhD')], max_length=5)),
                ('years_of_experience', models.CharField(choices=[('N', 'No Experince'), ('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('6', '6 Years'), ('7', '7 Years'), ('8', '8 Years'), ('9', '9 Years'), ('10', '10 Years'), ('10+', '10+ Years')], max_length=5)),
                ('salary_expectation', models.CharField(max_length=250)),
                ('cover_letter', models.TextField()),
                ('curriculum_vitae', models.FileField(upload_to='')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.Job')),
            ],
        ),
    ]
