# Generated by Django 2.2.5 on 2019-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
